# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../views/config_form/config_form.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ConfigForm(object):
    def setupUi(self, ConfigForm):
        ConfigForm.setObjectName("ConfigForm")
        ConfigForm.resize(968, 581)
        self.verticalLayout = QtWidgets.QVBoxLayout(ConfigForm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setContentsMargins(-1, -1, -1, 10)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_2 = QtWidgets.QLabel(ConfigForm)
        self.label_2.setMinimumSize(QtCore.QSize(125, 0))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_12.addWidget(self.label_2)
        self.dfLineEdit = QtWidgets.QLineEdit(ConfigForm)
        self.dfLineEdit.setObjectName("dfLineEdit")
        self.horizontalLayout_12.addWidget(self.dfLineEdit)
        self.dfSelectPath = QtWidgets.QPushButton(ConfigForm)
        self.dfSelectPath.setObjectName("dfSelectPath")
        self.horizontalLayout_12.addWidget(self.dfSelectPath)
        self.dfSave = QtWidgets.QPushButton(ConfigForm)
        self.dfSave.setEnabled(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/yes"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.dfSave.setIcon(icon)
        self.dfSave.setObjectName("dfSave")
        self.horizontalLayout_12.addWidget(self.dfSave)
        self.dfDefault = QtWidgets.QPushButton(ConfigForm)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/reload"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.dfDefault.setIcon(icon1)
        self.dfDefault.setObjectName("dfDefault")
        self.horizontalLayout_12.addWidget(self.dfDefault)
        self.verticalLayout.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setContentsMargins(-1, -1, -1, 10)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.vboxmanagePathLabel = QtWidgets.QLabel(ConfigForm)
        self.vboxmanagePathLabel.setMinimumSize(QtCore.QSize(125, 0))
        self.vboxmanagePathLabel.setObjectName("vboxmanagePathLabel")
        self.horizontalLayout_11.addWidget(self.vboxmanagePathLabel)
        self.vboxmanagePathLineEdit = QtWidgets.QLineEdit(ConfigForm)
        self.vboxmanagePathLineEdit.setMinimumSize(QtCore.QSize(200, 0))
        self.vboxmanagePathLineEdit.setObjectName("vboxmanagePathLineEdit")
        self.horizontalLayout_11.addWidget(self.vboxmanagePathLineEdit)
        self.vboxmanageSelectPath = QtWidgets.QPushButton(ConfigForm)
        self.vboxmanageSelectPath.setObjectName("vboxmanageSelectPath")
        self.horizontalLayout_11.addWidget(self.vboxmanageSelectPath)
        self.vboxmanageSave = QtWidgets.QPushButton(ConfigForm)
        self.vboxmanageSave.setEnabled(False)
        self.vboxmanageSave.setIcon(icon)
        self.vboxmanageSave.setObjectName("vboxmanageSave")
        self.horizontalLayout_11.addWidget(self.vboxmanageSave)
        self.vboxmanageDefault = QtWidgets.QPushButton(ConfigForm)
        self.vboxmanageDefault.setIcon(icon1)
        self.vboxmanageDefault.setObjectName("vboxmanageDefault")
        self.horizontalLayout_11.addWidget(self.vboxmanageDefault)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(-1, -1, -1, 10)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.vMnameLabel = QtWidgets.QLabel(ConfigForm)
        self.vMnameLabel.setMinimumSize(QtCore.QSize(125, 0))
        self.vMnameLabel.setObjectName("vMnameLabel")
        self.horizontalLayout_10.addWidget(self.vMnameLabel)
        self.vmnameLineEdit = QtWidgets.QLineEdit(ConfigForm)
        self.vmnameLineEdit.setMinimumSize(QtCore.QSize(300, 0))
        self.vmnameLineEdit.setObjectName("vmnameLineEdit")
        self.horizontalLayout_10.addWidget(self.vmnameLineEdit)
        self.vmnameSave = QtWidgets.QPushButton(ConfigForm)
        self.vmnameSave.setEnabled(False)
        self.vmnameSave.setIcon(icon)
        self.vmnameSave.setObjectName("vmnameSave")
        self.horizontalLayout_10.addWidget(self.vmnameSave)
        self.vmnameDefault = QtWidgets.QPushButton(ConfigForm)
        self.vmnameDefault.setIcon(icon1)
        self.vmnameDefault.setObjectName("vmnameDefault")
        self.horizontalLayout_10.addWidget(self.vmnameDefault)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        spacerItem = QtWidgets.QSpacerItem(20, 379, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.deleteIslandButton = QtWidgets.QPushButton(ConfigForm)
        self.deleteIslandButton.setMinimumSize(QtCore.QSize(0, 50))
        self.deleteIslandButton.setStyleSheet("width: 150px; height: 80px;")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/error"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.deleteIslandButton.setIcon(icon2)
        self.deleteIslandButton.setObjectName("deleteIslandButton")
        self.horizontalLayout_14.addWidget(self.deleteIslandButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_14)

        self.retranslateUi(ConfigForm)
        QtCore.QMetaObject.connectSlotsByName(ConfigForm)

    def retranslateUi(self, ConfigForm):
        _translate = QtCore.QCoreApplication.translate
        ConfigForm.setWindowTitle(_translate("ConfigForm", "Configuration"))
        self.label_2.setText(_translate("ConfigForm", "Data folder path:"))
        self.dfSelectPath.setText(_translate("ConfigForm", "Browse..."))
        self.dfSave.setText(_translate("ConfigForm", "Save"))
        self.dfDefault.setText(_translate("ConfigForm", "Restore default"))
        self.vboxmanagePathLabel.setText(_translate("ConfigForm", "Path to vboxmanage:"))
        self.vboxmanageSelectPath.setText(_translate("ConfigForm", "Browse..."))
        self.vboxmanageSave.setText(_translate("ConfigForm", "Save"))
        self.vboxmanageDefault.setText(_translate("ConfigForm", "Restore default"))
        self.vMnameLabel.setText(_translate("ConfigForm", "Island VM name:"))
        self.vmnameSave.setText(_translate("ConfigForm", "Save"))
        self.vmnameDefault.setText(_translate("ConfigForm", "Restore default"))
        self.deleteIslandButton.setText(_translate("ConfigForm", "Delete Island VM"))


