# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '..\views\image_authoring_form\image_authoring_form.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ImageAuthoringForm(object):
    def setupUi(self, ImageAuthoringForm):
        ImageAuthoringForm.setObjectName("ImageAuthoringForm")
        ImageAuthoringForm.setWindowModality(QtCore.Qt.WindowModal)
        ImageAuthoringForm.resize(589, 651)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(ImageAuthoringForm)
        self.verticalLayout_5.setSpacing(26)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.form_title = QtWidgets.QLabel(ImageAuthoringForm)
        font = QtGui.QFont()
        font.setPointSize(26)
        self.form_title.setFont(font)
        self.form_title.setObjectName("form_title")
        self.verticalLayout_5.addWidget(self.form_title)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.source_file = QtWidgets.QLineEdit(ImageAuthoringForm)
        self.source_file.setObjectName("source_file")
        self.horizontalLayout.addWidget(self.source_file)
        self.btn_select_source = QtWidgets.QPushButton(ImageAuthoringForm)
        self.btn_select_source.setObjectName("btn_select_source")
        self.horizontalLayout.addWidget(self.btn_select_source)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(13)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(ImageAuthoringForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.select_private_key = QtWidgets.QComboBox(ImageAuthoringForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.select_private_key.sizePolicy().hasHeightForWidth())
        self.select_private_key.setSizePolicy(sizePolicy)
        self.select_private_key.setCurrentText("")
        self.select_private_key.setObjectName("select_private_key")
        self.horizontalLayout_2.addWidget(self.select_private_key)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.private_key_password = QtWidgets.QLineEdit(ImageAuthoringForm)
        self.private_key_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.private_key_password.setObjectName("private_key_password")
        self.horizontalLayout_6.addWidget(self.private_key_password)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.verticalLayout_5.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(12)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.islands_version = QtWidgets.QLineEdit(ImageAuthoringForm)
        self.islands_version.setObjectName("islands_version")
        self.horizontalLayout_4.addWidget(self.islands_version)
        self.image_version = QtWidgets.QLineEdit(ImageAuthoringForm)
        self.image_version.setObjectName("image_version")
        self.horizontalLayout_4.addWidget(self.image_version)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.path_to_dest = QtWidgets.QLineEdit(ImageAuthoringForm)
        self.path_to_dest.setText("")
        self.path_to_dest.setObjectName("path_to_dest")
        self.horizontalLayout_3.addWidget(self.path_to_dest)
        self.btn_select_dest_path = QtWidgets.QPushButton(ImageAuthoringForm)
        self.btn_select_dest_path.setObjectName("btn_select_dest_path")
        self.horizontalLayout_3.addWidget(self.btn_select_dest_path)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.out_filename = QtWidgets.QLineEdit(ImageAuthoringForm)
        self.out_filename.setObjectName("out_filename")
        self.verticalLayout_2.addWidget(self.out_filename)
        self.note = QtWidgets.QTextEdit(ImageAuthoringForm)
        self.note.setObjectName("note")
        self.verticalLayout_2.addWidget(self.note)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.verticalLayout_5.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(12)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.publisher = QtWidgets.QLineEdit(ImageAuthoringForm)
        self.publisher.setObjectName("publisher")
        self.verticalLayout_3.addWidget(self.publisher)
        self.publisher_email = QtWidgets.QLineEdit(ImageAuthoringForm)
        self.publisher_email.setObjectName("publisher_email")
        self.verticalLayout_3.addWidget(self.publisher_email)
        self.verticalLayout_5.addLayout(self.verticalLayout_3)
        self.chk_seed_now = QtWidgets.QCheckBox(ImageAuthoringForm)
        self.chk_seed_now.setObjectName("chk_seed_now")
        self.verticalLayout_5.addWidget(self.chk_seed_now)
        self.progress_wrap = QtWidgets.QWidget(ImageAuthoringForm)
        self.progress_wrap.setVisible(False)
        self.progress_wrap.setObjectName("progress_wrap")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.progress_wrap)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.progressBar = QtWidgets.QProgressBar(self.progress_wrap)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_4.addWidget(self.progressBar)
        self.lbl_action = QtWidgets.QLabel(self.progress_wrap)
        self.lbl_action.setText("")
        self.lbl_action.setObjectName("lbl_action")
        self.verticalLayout_4.addWidget(self.lbl_action)
        self.verticalLayout_5.addWidget(self.progress_wrap)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(21)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.btn_cancel = QtWidgets.QPushButton(ImageAuthoringForm)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_cancel.setFont(font)
        self.btn_cancel.setStyleSheet("height: 35px")
        self.btn_cancel.setObjectName("btn_cancel")
        self.horizontalLayout_5.addWidget(self.btn_cancel)
        self.btn_go = QtWidgets.QPushButton(ImageAuthoringForm)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_go.setFont(font)
        self.btn_go.setStyleSheet("height: 35px; color: green;")
        self.btn_go.setObjectName("btn_go")
        self.horizontalLayout_5.addWidget(self.btn_go)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)

        self.retranslateUi(ImageAuthoringForm)
        QtCore.QMetaObject.connectSlotsByName(ImageAuthoringForm)

    def retranslateUi(self, ImageAuthoringForm):
        _translate = QtCore.QCoreApplication.translate
        ImageAuthoringForm.setWindowTitle(_translate("ImageAuthoringForm", "Dialog"))
        self.form_title.setText(_translate("ImageAuthoringForm", "Islands Image Authoring"))
        self.source_file.setPlaceholderText(_translate("ImageAuthoringForm", "Path to Islands image file"))
        self.btn_select_source.setText(_translate("ImageAuthoringForm", "Select image file"))
        self.label.setText(_translate("ImageAuthoringForm", "Select private key:"))
        self.private_key_password.setPlaceholderText(_translate("ImageAuthoringForm", "Private key password"))
        self.islands_version.setPlaceholderText(_translate("ImageAuthoringForm", "Islands version"))
        self.image_version.setPlaceholderText(_translate("ImageAuthoringForm", "Image version"))
        self.path_to_dest.setPlaceholderText(_translate("ImageAuthoringForm", "Path to destination folder"))
        self.btn_select_dest_path.setText(_translate("ImageAuthoringForm", "Select destination folder"))
        self.out_filename.setPlaceholderText(_translate("ImageAuthoringForm", "Output file name"))
        self.note.setPlaceholderText(_translate("ImageAuthoringForm", "Place for note"))
        self.publisher.setPlaceholderText(_translate("ImageAuthoringForm", "Enter your name or nickname"))
        self.publisher_email.setPlaceholderText(_translate("ImageAuthoringForm", "Enter your email"))
        self.chk_seed_now.setText(_translate("ImageAuthoringForm", "Start seeding immediately"))
        self.btn_cancel.setText(_translate("ImageAuthoringForm", "Cancel"))
        self.btn_go.setText(_translate("ImageAuthoringForm", "GO!"))

