"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['main.py']

DATA_FILES = [
    'images/icon.icns',
    'os_defaults/linux.json',
    'os_defaults/mac.json',
    'os_defaults/windows.json',
    'default_config.json',
    'version'
]
PLIST = {'CFBundleDisplayName': 'Islands', 'CFBundleName': 'Islands'}
OPTIONS = {'iconfile': 'images/icon.icns', 'plist': PLIST}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
